export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SIGNUP_FAIL = 'REGISTER_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const GET_TRANSACTION_TYPES_FAIL = 'GET_TRANSACTION_TYPES_FAIL';
export const GET_TRANSACTION_TYPES_SUCCESS = 'GET_TRANSACTION_TYPES_SUCCESS';

export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

export const GET_YEAR = 'GET_YEAR';

export const ADD_TRANSACTION_FAIL = 'ADD_TRANSACTION_FAIL';
export const ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS';


